### ISSUE TITLE
Unsupported version issue when running under JDK 1.7

### ISSUE THREAD

**Issue by maxcellent** [maxcellent/lamma#9]
Caused by: java.lang.UnsupportedClassVersionError: io/lamma/DayOfWeek : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_72]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_72]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_72]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_72]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_72]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_72]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_72]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_72]

**Comment by maxcellent** [comment]
This is because prior to 2.2.3, the project is compiled to target version = 1.8.

Version 2.2.3 has fixed this problem
